version: '3.9'
services:
  omniedge-adonis-pg:
    image: postgres:13.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 3s
      retries: 10
  omniedge-adonis-pg-migration:
    depends_on:
      - omniedge-adonis-pg
    build:
      context: ../..
      dockerfile: docker/local/pg-migration-Dockerfile

  omniedge-adonis:
    depends_on:
      - omniedge-adonis-pg
      - omniedge-adonis-pg-migration
    build:
      context: ../..
      dockerfile: docker/local/Dockerfile
    ports:
      - "53333:3333"
