export const ErrorCode = {
  common: {},
  auth: {
    E_EMAIL_PASSWORD_NOT_MATCH: 'E_EMAIL_PASSWORD_NOT_MATCH',
    E_SAVE_USER: 'E_SAVE_USER',
    E_GOOGLE_AUTH_FAIL: 'E_GOOGLE_AUTH_FAIL',
    E_USER_EXISTED: 'E_USER_EXISTED',
    E_USER_BLOCKED: 'E_USER_BLOCKED',
    E_TOKEN_INVALID: 'E_TOKEN_INVALID',
    E_TOKEN_EXPIRED: 'E_TOKEN_EXPIRED',
    F_EMAIL_SEND: 'F_EMAIL_SEND',
  },
}
